apiVersion: v1
kind: ConfigMap
metadata:
  name: watcher-config
  namespace: statuz
data:
  watcher_config.yaml: |
    global:
      namespace: statuz
      prometheus:
        basic-auth: disabled
        endpoint: prometheus:9090
    watcher:
      endpoints:
        - name: google-bd
          type: webpage
          target: https://www.google.com.bd/
        - name: grafana-web
          type: api
          method: GET
          target: https://grafana.com/healthz
        - name: cloudflare-dns
          type: ping
          target: 1.1.1.1
