name: release docker images

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: release docker images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/386
          - linux/amd64
          - linux/arm/v6
          - linux/arm/v7
          - linux/arm64/v8

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: release watcher image to quay.io
        uses: statuzproj/actions/quay-multi-arch@main
        with:
          service_name: watcher
          dockerfile_path: svc/watcher/Dockerfile
          tag: ${{ github.ref_name }}
          quay_registry: ${{ vars.QUAY_REGISTRY }}
          quay_username: ${{ secrets.QUAY_USERNAME }}
          quay_password: ${{ secrets.QUAY_PASSWORD }}

      - name: release genie image to quay.io
        uses: statuzproj/actions/quay-multi-arch@main
        with:
          service_name: genie
          dockerfile_path: svc/genie/Dockerfile
          tag: ${{ github.ref_name }}
          quay_registry: ${{ vars.QUAY_REGISTRY }}
          quay_username: ${{ secrets.QUAY_USERNAME }}
          quay_password: ${{ secrets.QUAY_PASSWORD }}
